---
aws-region: &aws-region eu-west-1

groups:
- name: dependencies
  jobs:
  - bump-golang
  - bump-mariadb
  - bump-mysql
  - bump-postgresql
  - bump-boost
  - bump-libpcre2
- name: shipit
  jobs:
  - build-rc
  - create-final-patch

resources:
- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: ((github.ssh_key))
    branch: main

- name: version
  type: semver
  icon: tag
  source:
    bucket: backup-and-restore-sdk-releases
    region_name: *aws-region
    key: current-dev-version
    access_key_id: ((aws_credentials.access_key_id))
    secret_access_key: ((aws_credentials.secret_access_key))

- name: release
  type: s3
  icon: database
  source:
    bucket: backup-and-restore-sdk-releases
    regexp: backup-and-restore-sdk-(.*).tgz
    region_name: *aws-region
    access_key_id: ((aws_credentials.access_key_id))
    secret_access_key: ((aws_credentials.secret_access_key))

- name: slack-cryo-notification
  type: slack-notification
  icon: bell-ring
  source:
    url: ((slack.webhook))

- name: backup-and-restore-sdk-release-main
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))
    branch: main

- name: biweekly-gate
  type: gitgat
  icon: gate-and
  source:
    uri: https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release.git
    branch: main
    since: 2 weeks

- name: github-release
  type: github-release
  icon: rocket
  source:
    user: cloudfoundry-incubator
    repository: backup-and-restore-sdk-release
    drafts: true
    access_token: ((github.access_token))

- name: golang-release
  type: git
  icon: tag
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    tag_filter: v*

- name: daily-trigger
  type: time
  source:
    days: [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday' ]

jobs:
- name: build-rc
  serial: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
      trigger: true
      version: every
    - get: version
      params: {pre: rc}
  - task: create-dev-release
    file: backup-and-restore-sdk-release-main/ci/tasks/create-dev-release/task.yml
    input_mapping:
      backup-and-restore-sdk-release: backup-and-restore-sdk-release-main
    params:
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
  - put: release
    params:
      file: backup-and-restore-sdk-release-build/backup-and-restore-sdk-*.tgz
  - put: version
    params: {file: version/number}

- name: create-final-patch
  serial: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: biweekly-gate
      trigger: true
    - get: backup-and-restore-sdk-release-main
      passed: [build-rc]
    - get: version
      passed: [build-rc]
      params: {bump: patch}
    - get: cryogenics-concourse-tasks
  - task: create-final-release
    file: cryogenics-concourse-tasks/bosh-tasks/create-release/task.yml
    input_mapping:
      release-repo: backup-and-restore-sdk-release-main
    output_mapping:
      updated-release-repo: backup-and-restore-sdk-final-release
      updated-release-tarball: backup-and-restore-sdk-final-release-tarball
    params:
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
      GIT_USERNAME: Backup & Restore Concourse
      GIT_EMAIL: cf-lazarus@pivotal.io
      FINAL: true
      RELEASE_NAME: backup-and-restore-sdk
  - task: create-release-notes
    file: cryogenics-concourse-tasks/release-automation/release-notes/task.yml
    input_mapping:
      git-repo: backup-and-restore-sdk-release-main
    params:
      USE_LATEST_PUBLISHED_TAG: true
  - task: format-release-notes
    file: cryogenics-concourse-tasks/release-automation/format-release-notes/task.yml
    input_mapping:
      template-folder: cryogenics-concourse-tasks
    params:
      TEMPLATE_PATH: release-automation/release-notes-templates/release-notes-auto.md.erb
  - put: backup-and-restore-sdk-release-main
    params:
      repository: backup-and-restore-sdk-final-release
      merge: true
      tag: version/number
      tag_prefix: v
  - put: release
    params:
      file: backup-and-restore-sdk-final-release-tarball/backup-and-restore-sdk-*.tgz
  - put: github-release
    params:
      name: version/number
      tag: version/number
      body: release-notes/release-notes.md
      tag_prefix: v
      globs:
      - backup-and-restore-sdk-final-release-tarball/backup-and-restore-sdk-*.tgz
  - put: version
    params: {file: version/number}
  - load_var: version-tag
    file: version/number
  - load_var: github-release-url
    file: github-release/url
  - put: slack-cryo-notification
    params:
      text: |
        A new release for $BUILD_PIPELINE_NAME has been published!
        Release `((.:version-tag))` is now available <((.:github-release-url))|here>
        View the pipeline <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>

# Dependency bumps
- name: bump-golang
  plan:
  - in_parallel:
    - get: cryogenics-concourse-tasks
    - get: golang-release
      trigger: true
    - get: backup-and-restore-sdk-release-main
  - task: bosh-vendor-package
    file: cryogenics-concourse-tasks/deps-automation/bosh-vendor-package/task.yml
    input_mapping:
      release: backup-and-restore-sdk-release-main
      vendored-package-release: golang-release
    params:
      VENDORED_PACKAGE_NAME: golang-1-linux
      VENDOR_UPDATES_BRANCH: golang-vendor-updates
      COMMIT_USERNAME: bump-golang CI job
      COMMIT_USEREMAIL: mapbu-cryogenics@groups.vmware.com
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
  - put: backup-and-restore-sdk-release-main
    params:
      repository: release-with-updated-vendored-package
      branch: golang-vendor-updates
      force: true
  - task: create-golang-vendor-pull-request
    file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
    params:
      BASE: main
      BRANCH: golang-vendor-updates
      LABELS: ci,bump-golang
      TITLE: Update vendored package golang-1-linux
      MESSAGE: |
        This is an automatically generated Pull Request from the Cryogenics CI Bot.

        I have detected a new version of [golang-release](https://github.com/bosh-packages/golang-release) and automatically bumped
        this package to benefit from the latest changes.

        If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
    input_mapping:
      source-repo: backup-and-restore-sdk-release-main

- name: bump-mariadb
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
    - get: daily-trigger
      trigger: true

  - task: bump-mariadb
    file: backup-and-restore-sdk-release-main/ci/tasks/bump-generic/task.yml
    input_mapping:
      task-repo: backup-and-restore-sdk-release-main
      bump-repo: backup-and-restore-sdk-release-main
    vars:
      bump-script: scripts/autobump-mariadb.sh
    params:
      PR_BASE: main
      PR_LABELS: ci

      GH_TOKEN: ((github.access_token))
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))

- name: bump-mysql
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
    - get: daily-trigger
      trigger: true

  - task: bump-mysql
    file: backup-and-restore-sdk-release-main/ci/tasks/bump-generic/task.yml
    input_mapping:
      task-repo: backup-and-restore-sdk-release-main
      bump-repo: backup-and-restore-sdk-release-main
    vars:
      bump-script: scripts/autobump-mysql.sh
    params:
      PR_BASE: main
      PR_LABELS: ci

      GH_TOKEN: ((github.access_token))
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))

- name: bump-postgresql
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
    - get: daily-trigger
      trigger: true

  - task: bump-postgresql
    file: backup-and-restore-sdk-release-main/ci/tasks/bump-generic/task.yml
    input_mapping:
      task-repo: backup-and-restore-sdk-release-main
      bump-repo: backup-and-restore-sdk-release-main
    vars:
      bump-script: scripts/autobump-postgresql.sh
    params:
      PR_BASE: main
      PR_LABELS: ci

      GH_TOKEN: ((github.access_token))
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))

- name: bump-boost
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
    - get: daily-trigger
      trigger: true

  - task: bump-boost
    file: backup-and-restore-sdk-release-main/ci/tasks/bump-generic/task.yml
    input_mapping:
      task-repo: backup-and-restore-sdk-release-main
      bump-repo: backup-and-restore-sdk-release-main
    vars:
      bump-script: scripts/autobump-boost.sh
    params:
      PR_BASE: main
      PR_LABELS: ci

      GH_TOKEN: ((github.access_token))
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))

- name: bump-libpcre2
  plan:
  - in_parallel:
    - get: backup-and-restore-sdk-release-main
    - get: daily-trigger
      trigger: true

  - task: bump-libpcre2
    file: backup-and-restore-sdk-release-main/ci/tasks/bump-generic/task.yml
    input_mapping:
      task-repo: backup-and-restore-sdk-release-main
      bump-repo: backup-and-restore-sdk-release-main
    vars:
      bump-script: scripts/autobump-libpcre2.sh
    params:
      PR_BASE: main
      PR_LABELS: ci

      GH_TOKEN: ((github.access_token))
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
