---
resource_types:
- name: pr-queue
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: current-pr
  type: pr-queue
  source:
    repository: cloudfoundry-incubator/backup-and-restore-sdk-release
    access_token: ((github.access_token))

- name: current-pr-checks
  type: pr-queue
  source:
    repository: cloudfoundry-incubator/backup-and-restore-sdk-release
    access_token: ((github.access_token))
    track_checks: true

- name: bbr-sdk-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))

- name: cryogenics-tasks
  type: git
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: ((github.ssh_key))

- name: slack-cryo-notification
  type: slack-notification
  icon: bell-ring
  source:
    url: ((slack.webhook))

jobs:
- name: test-open-pr
  plan:
  - get: bbr-sdk-repo
  - get: current-pr
    trigger: true

  - load_var: pr-info
    file: current-pr/info.json

  - set_pipeline: backup-and-restore-sdk-release-test-prs
    file: bbr-sdk-repo/ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
    vars:
      branch: ((.:pr-info.branch))
      # Add any other variables required by your testing pipeline

- name: merge-pr
  plan:
  - get: cryogenics-tasks
  - get: current-pr-checks
    trigger: true

  - load_var: pr-info
    file: current-pr-checks/info.json

  - task: all-checks-passing
    file: cryogenics-tasks/tasks/pr-checks-passing/task.yml
    params:
      GH_TOKEN: ((github.access_token))
      PR: ((.:pr-info.number))
      REPO: ((.:pr-info.owner))/((.:pr-info.repository))
      CHECKS:
      - set-pipeline
      - unit-tests
      - contract-tests
      - system-tests-external-dbs-gcp
      - system-tests-external-dbs-rds
      - system-tests-internal-dbs
      - system-tests-blobstore-backuper
      - EasyCLA
      - security/snyk (mrdavidlaing)

  - task: merge-pr
    file: cryogenics-tasks/github-automation/merge-pr/task.yml
    input_mapping:
      cryogenics-concourse-tasks: cryogenics-tasks
    params:
      DELETE: TRUE
      AUTHOR: dependabot
      GH_TOKEN: ((github.access_token))
      PR_REF: ((.:pr-info.pr-url))
      PROJECT_NAME: BBR-SDK

    on_failure:
      put: slack-cryo-notification
      params:
        text: |
          *BBR-SDK:* A PR failed to be merged automatically (tests passed; probably merging conflicts?). You can review it <((.:pr-info.pr-url))|*here*>.

    on_success:
      put: slack-cryo-notification
      params:
        text: |
          *BBR-SDK:* A PR was merged automatically. You can review it <((.:pr-info.pr-url))|*here*>.

  - task: deliver-stories
    file: cryogenics-tasks/tracker-automation/deliver-stories/task.yml
    params:
      TRACKER_API_TOKEN: ((tracker.api_token))
      TRACKER_PROJECT_ID: ((tracker.project_id))
      GIT_REPOSITORY: ((.:pr-info.owner))/((.:pr-info.repository))

  - task: accept-stories
    file: cryogenics-tasks/tracker-automation/accept-stories/task.yml
    params:
      TRACKER_API_TOKEN: ((tracker.api_token))
      TRACKER_PROJECT_ID: ((tracker.project_id))
      GIT_REPOSITORY: ((.:pr-info.owner))/((.:pr-info.repository))
