---
resource_types:
- name: pr-queue
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: every-5-min
  type: time
  source: {interval: 5m}

- name: current-pr
  type: pr-queue
  source:
    repository: cloudfoundry-incubator/backup-and-restore-sdk-release
    access_token: ((github.access_token))

- name: some-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))

- name: cryogenics-tasks
  type: git
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: ((github.ssh_key))

jobs:
- name: test-open-pr
  plan:
  - get: some-repo
  - get: current-pr
    trigger: true

  - try:
    # When the last open PR is closed/merged, a new "empty" version is generated
    # To handle this try to read info.json. Only if it succeeds, continue exec.
      load_var: pr-info
      file: current-pr/info.json
      on_success:
        set_pipeline: backup-and-restore-sdk-release-test-prs
        file: some-repo/ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
        vars:
          branch: ((.:pr-info.branch))
          # Add any other variables required by your testing pipeline

- name: merge-pr
  plan:
  - get: some-repo
  - get: current-pr
  - get: every-5-min
    trigger: true

  - try:
    # When the last open PR is closed/merged, a new "empty" version is generated
    # To handle this try to read info.json. Only if it succeeds, continue exec.
      load_var: pr-info
      file: current-pr/info.json
      on_success:
        task: merge-pr
        file: cryogenics-tasks/tasks/automerge/task.yml
        params:
          GH_TOKEN: ((github.access_token))
          PR: ((.:pr-info.number))
          REPO: ((.:pr-info.owner))/((.:pr-info.repository))
          CHECKS:
            - set-pipeline
            - unit-tests
            - contract-tests
            - system-tests-external-dbs-gcp
            - system-tests-external-dbs-rds
            - system-tests-internal-dbs
            - system-tests-blobstore-backuper
            - merge-pr
